default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maptivity_be_development
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

test:
  <<: *default
  database: maptivity_be_test
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["RDS_DB_NAME"] %>
    username: <%= ENV["RDS_USERNAME"] %>
    password: <%= ENV["RDS_PASSWORD"] %>
    host: <%= ENV["RDS_HOSTNAME"] %>
    port: <%= ENV["RDS_PORT"] || '5432' %>
  cache:
    <<: *primary_production
    database: maptivity_be_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: maptivity_be_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: maptivity_be_production_cable
    migrations_paths: db/cable_migrate
